assert calculate_priority("high", 10) == "critical"
assert calculate_priority("high", 2) == "high"
assert calculate_priority("low", 10) == "high"
assert calculate_priority("medium", 1) == "medium"
assert calculate_priority("low", 3) == "medium"
assert calculate_priority("low", 1) == "low"